const { chromium } = require('playwright');

const urls = [
  'https://sanand0.github.io/tdsdata/js_table/?seed=7',
  'https://sanand0.github.io/tdsdata/js_table/?seed=8',
  'https://sanand0.github.io/tdsdata/js_table/?seed=9',
  'https://sanand0.github.io/tdsdata/js_table/?seed=10',
  'https://sanand0.github.io/tdsdata/js_table/?seed=11',
  'https://sanand0.github.io/tdsdata/js_table/?seed=12',
  'https://sanand0.github.io/tdsdata/js_table/?seed=13',
  'https://sanand0.github.io/tdsdata/js_table/?seed=14',
  'https://sanand0.github.io/tdsdata/js_table/?seed=15',
  'https://sanand0.github.io/tdsdata/js_table/?seed=16',
];

(async () => {
  // Launch a headless (invisible) browser
  const browser = await chromium.launch();
  const page = await browser.newPage();

  let grandTotal = 0;

  for (const url of urls) {
    await page.goto(url, { waitUntil: 'networkidle' });

    // Wait for the table to appear (it's dynamically generated by JavaScript)
    await page.waitForSelector('table');

    // Grab all table cell text, parse numbers, and sum them
    const pageSum = await page.evaluate(() => {
      const cells = document.querySelectorAll('table td');
      let total = 0;
      cells.forEach(cell => {
        const val = parseFloat(cell.innerText.trim());
        if (!isNaN(val)) total += val;
      });
      return total;
    });

    console.log(`Sum for ${url}: ${pageSum}`);
    grandTotal += pageSum;
  }

  console.log(`Total sum across all pages: ${grandTotal}`);
  await browser.close();
})();
